Concordium/concordium-rosetta

- Jenkinsfile
- build-deb.sh
- macos.Jenkinsfile
- windows.Jenkinsfile
Publish native binaries for Windows and Debian.
Add a pipeline for building a Windows native binary and publish it to S3. Also make the default (Docker) pipeline also extract the binary and put it into a Debian package that is uploaded to S3.
> Jenkins: Add Windows, macOS, and Debian pipelines

- src/main.rs
Make naming of env vars consistent with existing projects and ensure that all settings are settable with env vars.
Add missing vars for a few settings and add prefix `CONCORDIUM_ROSETTA_` to all vars.
> Add prefix to environment variables

- .github/workflows/ci.yaml
- Cargo.lock
- Cargo.toml
- README.md
- macos.Jenkinsfile
- src/main.rs
- windows.Jenkinsfile
As `clap` v3 is on par with or better than `structopt`, that project [has entered maintenance mode](https://github.com/TeXitoi/structopt#maintenance) and will not have things like the weird way it handles env vars fixed.
Upgraded `clap` to v. `3.1` and removed dependency on `structopt`.
> Migrate structopt to clap v3

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/handler_error.rs
The rosetta-cli tool checks that error descriptions are not empty, which presumably means that is part of the API.
Add an error description string to conform to the API.
> Error descriptions have to be non-empty.

- fmt.sh
- package.json
- rosetta/docs/Allow.md
- rosetta/src/models/allow.rs
- src/api/network.rs
Make fields of generated struct use the correct types. 
Picked changes to generated `Allow` type from version generated by a more recent version of the rosetta spec.
It seems like there's some bug in the generator that makes it generate fields of type plain `serde_json::Value` instead of the proper types in the `Allow` struct. Picking the changes to `Allow`'s model from commit https://github.com/coinbase/rosetta-specifications/commit/ce6898659de0f79c350034db6ac938e12805302f#diff-80521b2ac2125e10a84393ae746d6f0d993979c8a974dc320b913f8bb2fd32b5 makes it generate it correctly. Before the model change, all non-builtin types were used as a parameter to `Vec`, so that could be what's triggering the bug.
This also means that this change won't be reverted by a future upgrade of the Rosetta spec.
> Generate Allow type with correct field types

- README.md
We have had questions by a user on why the build was failing, and it was due to submodules not being checked out.
This makes the requirement more explicit.
Better documentation.
> Add warning about submodules

- src/api/account.rs
- src/api/amount.rs
- src/api/block.rs
- src/api/construction.rs
- src/api/transaction.rs
The currently used type `i64` is wide enough for the time being but may not be so in the distant future. Using `i128` instead ensures that any `u64` value stays represented correctly.
Change all `i64` variables for amounts to `i128`.
Rosetta represents amounts as strings so no changes to generated code are required.
Requested in [this comment](https://github.com/Concordium/concordium-rosetta/pull/18/files#r864980096).
> Ensure that all amount casts are sound

- README.md
- tools/transfer-client/README.md
Improve documentation, particularly on failure handling.
Gave a pass on the root README and added a section on how Rosetta handles and not handles failure with examples.
Also added a section to the README of the `transfer-client` tool on how to use keys exported from the mobile wallet.
Resolves #12.
> Improve documentation

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/handler_error.rs
- tools/transfer-client/README.md
Make it easier for clients to understand when the response is an error. Currently they can only do it by parsing the JSON payload.
Respond with non-OK HTTP status codes on error. The status code also includes a hint on what kind of error it is.
Resolves #14.
> Respond with non-OK HTTP status codes on error

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/handler_error.rs
- src/route.rs
- tools/transfer-client/src/main.rs
Log incoming requests to add debugging/monitoring abilities to the service.
Enable the default logging filter in the warp router.
The default logger implementation logs on INFO level. This is appropriate as the debug level includes a whole lot more data on the data frame level.
Resolves #15.
> Log all requests and error responses to warp server

- src/api/network.rs
Ensure that the value of `current_block_timestamp` is always well defined.
The existing solution defaulted to -1 when the 'last_finalized_time' of 'consensus status' was None. This happens if the node wasn't online when the block was finalized and breaks the Rosetta CLI.
The slot time of the last finalized block, which is objectively agreed upon across all nodes, is now used instead.
> Use slot time of last finalized block for 'current_block_timestamp'

- src/api/transaction.rs
Make the schedule metadata of transfers with schedule easier to understand.
Based on [this](https://github.com/Concordium/concordium-rosetta/pull/33#discussion_r892895884) comment, change
```
"amounts": [
[
1665403200000,
"100000000"
],
...
]
```
into
```
"amounts": [
{
timestamp: 1665403200000,
amount_uccd: "100000000"
},
...
]
```
The name (and unit of) `timestamp` is chosen for consistency with the `current_block_timestamp` field of  [`/network/status`](https://www.rosetta-api.org/docs/models/NetworkStatusResponse.html). The name `amount_uccd` is consistent with other similar uses.
> Improve format of metadata for transfers with schedule

- .github/workflows/ci.yaml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- Dockerfile
- Jenkinsfile
- README.md
- macos.Jenkinsfile
- src/main.rs
- tools/query-account/Cargo.lock
- tools/query-account/Cargo.toml
- tools/transfer-client-direct/Cargo.lock
- tools/transfer-client-direct/Cargo.toml
- tools/transfer-client-direct/src/main.rs
- tools/transfer-client/Cargo.lock
- tools/transfer-client/Cargo.toml
- windows.Jenkinsfile
Bump Node SDK to fix a parsing bug. This bumps the minimum Rust version to 1.56.
Also ran 'cargo update' to update dependencies (and remove pinnings that are no longer needed).
> Bump Node SDK

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/api/block.rs
Enable clients to determine the baker of a given block using the `/block` endpoint.
I vaguely recall that this was "requested" (or at least enquired) some time ago. In any case, I think it's a reasonable add.
Add field `baker_id` in metadata of `BlockResponse`. Resolves #47.
> Emit baker ID in metadata of BlockResponse

- .github/workflows/ci.yaml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/api/block.rs
- src/api/query.rs
- src/api/transaction.rs
- tools/transfer-client-direct/Cargo.lock
- tools/transfer-client-direct/src/main.rs
- tools/transfer-client/Cargo.lock
Upgrade Rosetta to support protocol version 5.
This needs
- upgrade rust toolchain to 1.62 since the SDK requires it
- update the SDK to latest that supports protocol 5.
> Upgrade Rosetta to support protocol version 5.

- .github/workflows/ci.yaml
Address GitHub Actions [deprecation warnings](https://github.com/Concordium/concordium-rosetta/actions/runs/4261439548).
The checkout action is updated to deprecation warnings in the workflow output. The Rust toolchain action seems abandoned and is also redundant because [rustup is installed](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md) in the VMs already.
Bump/replace actions.
> CI: Update actions

- docker-compose.yaml
Ensure that default build args in `docker-compose.yaml` work.
Upgraded default build image from rust version 1.56 to 1.62 as this is the minimum supported version as of commit 4c7d91dabae31a8c58a26ff8d667dd7eecc0a8e8.
> Compose: Bump default build image

- .github/workflows/ci.yaml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/api/transaction.rs
- tools/transfer-client-direct/Cargo.lock
- tools/transfer-client/Cargo.lock
Update the rust fmt version to match our other Rust repos.
- Set rust fmt to `2023-04-01`
- Set MSRV to `1.64` to improve error messages if you have an older version. The version comes from the rust-sdk.
- Also replaces the deprecated type alias `ModuleRef` with the new `ModuleReference`.
- Regenerate `Cargo.lock` to get around build issues from old versions of dependencies.
> Set Rust fmt to `2023-04-01` and set MSRV to `1.64`

- README.md
- docker-compose.yaml
- tools/rosetta-cli-docker/Dockerfile
- tools/transfer-client/README.md
Simplify the process of running the `check:data` check against the Rosetta implementation.
Added a deployment `rosetta-cli-check-data` under the profile `check-data`.
Tested against local node (deployed using [`concordium-docker`](https://github.com/bisgardo/concordium-docker)) with command
```shell
ROSETTA_IMAGE=concordium/rosetta:1.1.0-1 CONCORDIUM_ROSETTA_GRPC_PORT=11000 CONCORDIUM_ROSETTA_NETWORK=rosetta docker compose --profile=check-data up
```
and also excluding the profile.
> Docker Compose: Add optional deployment of 'rosetta-cli' running 'check:data'

- .github/workflows/ci.yaml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- Makefile
- README.md
- docker-compose.yaml
- src/api/block.rs
- src/api/construction.rs
- src/api/transaction.rs
- tools/transfer-client-direct/Cargo.lock
- tools/transfer-client/Cargo.lock
- tools/transfer-client/src/lib.rs
- tools/transfer-client/src/main.rs
Updates the Rust SDK submodule to point to the latest version with the changes for protocol version 7. Also gets rid of a few clippy lint warnings and deprecation warnings due to the SDK changes. Also updates to Rust 1.73 as the SDK requires this.
> Update Rust SDK submodule

- Dockerfile
> Trying to fix docker build

- .github/workflows/release.yaml
Migrate rosetta to github actions
Add github actions workflow to build rosetta for windows, mac, linux, and docker
_Remove if not applicable.
By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf
> Ekw/sre 999/release rosetta

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- rosetta/Cargo.toml
- src/api/block.rs
- src/api/network.rs
- src/api/query.rs
- src/api/transaction.rs
- src/version.rs
- tools/query-account/Cargo.lock
- tools/query-account/Cargo.toml
- tools/transfer-client-direct/Cargo.lock
- tools/transfer-client/Cargo.lock
Closes #72 
Support protocol version 8.
- The `configure_baker` operation can have metadata with the `suspended` boolean, indicating when a validator is manually suspended or resumed.
- New `validator_primed_for_suspension` and `validator_suspended` operation types indicate when a validator is primed for suspension or suspended automatically as part of the tokenomics transaction.
- Update dependencies
- Change `/node/options` to report the node and middleware versions accurately. (i.e. query the node for the node version, and use the Cargo.toml version for the middleware version.)
- Bump the version number.
> P8 support

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/api/transaction.rs
- tools/transfer-client-direct/Cargo.toml
- tools/transfer-client/Cargo.toml
Currently, concordium-rosetta won't work with newer version of rust sdk. This PR is basically bumping up the sdk version and ensuring there are no compilation errors. Anything with the PLT operations are marked with todo macro.
Making sure the concordium-rosetta build fine and can be run without any issue pointing to the newer rust sdk version
- [ x ] My code follows the style of this project.
- [ x ] The code compiles without warnings.
- [ x ] I have performed a self-review of the changes.
- [ x ] I have documented my code, in particular the intent of the
- [ x ] (If necessary) I have updated the CHANGELOG.
> Ensuring concordium rosetta can work with the newer sdk version
